### ISSUE TITLE
calculate page break

### ISSUE THREAD

**Issue by juergenhah** [juergenhah/sideprojects#2]
### Prerequisits
* A pdf document is generated using html2pdf npm package https://www.npmjs.com/package/html2pdf-ts 
* The HTML document is generated with vue3 components having different width and heights
* The height of the vue3 components is dependent on the data. Such that there is no pre defined height of a vue-component. 

## Task 
Optimise the pages of a PDF-document.

- [ ] Create an example to show the behavior: 
     - [ ] Having several HTML divs with different height in a Vue3 template, where the summarized height of div elements is greater than 1 A4-PDF page.
- [ ] Create an algorithm that calculates the height of each div
- [ ] Add div's to the actual A4-PDF page as long there is enough space on the A4-PDF page. If the height of the div element  is greater than the available A4 PDF height, create a new A4 PDF page and add the div to the new page. Repeat this as long all div's are included on pages in one A4-PDF document.

**Comment by uebergangml** [comment]
würde es auf 2-6 tage schätzen:
2-3 Tage für die Implementierung
3 Tage buffer für special cases
